server:
  port: 8080

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/chars?useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: my-secret-pw
        slave_1:
          url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: my-secret-pw




logging:
  level:
#    org.springframework: DEBUG
    com.lz.boot: debug

mybatis-plus:
  type-aliases-package: com.lz.boot.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
