server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chars?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    initialSize: 2
    minIdle: 2
    maxActive: 2


#logging:
#  level:
#    org.springframework: DEBUG

mybatis-plus:
  type-aliases-package: com.lz.boot.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
