server:
  port: 8989


spring:
  datasource:
    master:
      password: my-secret-pw
      url: jdbc:mysql://127.0.0.1:3306/chars?useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      type: com.alibaba.druid.pool.DruidDataSource
    slave:
      - key: slave1
        password: my-secret-pw
        url: jdbc:mysql://127.0.0.1:3306/chars?useUnicode=true&characterEncoding=UTF-8
        idle-timeout: 20000
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        type: com.alibaba.druid.pool.DruidDataSource
      - key: slave2
        password: my-secret-pw
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        username: root

mybatis:
#mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.lz.boot.entity
#logging:
#  level:
#    org.springframework: DEBUG
