server:
  port: 8080

spring:
  datasource:
    schema[0]: classpath:sql/user.sql
    schema[1]: classpath:sql/insert.sql
    initialization-mode: always
  h2:
    console:
      enabled: true

mybatis-plus:
  type-aliases-package: com.lz.boot.entity
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %red [%X{requestId}] [%thread] %-5level %logger{50} - %msg  %n"
  level:
    org.springframework.web: DEBUG
    com.lz.boot: debug