DROP TABLE IF EXISTS user;

CREATE TABLE user
(
    id VARCHAR(20) NOT NULL COMMENT '主键ID',
    name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
    age INT(11) NULL DEFAULT NULL COMMENT '年龄',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    creator VARCHAR(50) NULL DEFAULT NULL COMMENT '创建人',
    create_time DATETIME NULL DEFAULT NULL COMMENT '创建时间',
    is_delete INT(1) NULL DEFAULT NULL COMMENT '逻辑删除标识',
    PRIMARY KEY (id)
);